name: Triggering Events

#me eka eka trigerring action walt adlawa krnna one de krla blnna oen
on:
    push:
        branches:
            - "example-branches/*"
    
    pull_request:
        types:
            - opened
            - synchronize 
            - reopened
        paths:
            - ".github/workflows/filters/*.md"
            - ".github/workflows/filters/!filters/*.txt"

    schedule:
        - cron: "0 0 * * *" # midnight utc
        
    workflow_dispatch:

#me job ek run wenne workflow ek manually run kalama echchri , anikwa wenama e e event ekt anuwai run wenne
jobs:
    echo-event:
        runs-on: ubuntu-24.04
        steps:
            - name: Dump full event JSON
              run: |
                echo "=== $GITHUB_EVENT_NAME payload ==="
                cat "$GITHUB_EVENT_PATH"

            - name: testing another console log
              run: echo "This line was added to test another step on the trigger event"
                